version: '3.5'
services:
  eureka-server:
    image: 'eureka-server'
    ports:
      - '8082:8082'
    networks:
      - network-eureka

  subscription-service:
      image: 'subscription-service'
      ports:
       - '8081:8081'
      environment:
       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8082/eureka/
       SPRING_DATA_MONGODB_HOST: mongo
      links:
        - mongo
      depends_on:
        - mongo
      networks:
        - network-eureka
  mongo:
    image: 'mongo'
    restart: always
    container_name: 'newsletter-mongo-database'
    volumes:
     - ./data/db:/var/micro-data/mongodb/data/db
    ports:
      - '27017:27017'
    networks:
      - network-eureka
  event-service:
    image: 'event-service'
    ports:
      - '8085:8085'
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8082/eureka/
    networks:
      - network-eureka
  email-service:
    image: 'email-service'
    ports:
      - '8083:8083'
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8082/eureka/
    networks:
      - network-eureka
networks:
  network-eureka:
        driver: bridge